version: 2
updates:
  # Maintain dependencies for npm.
  - package-ecosystem: 'npm'
    assignees:
      - 'lumirlumir'
    # Specify all directories from the current layer and below recursively, using globstar, for locations of manifest files.
    directories:
      - '**/*'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
      next:
        patterns:
          - 'next'
          - '@next/*'
    reviewers:
      - 'lumirlumir'
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'Asia/Seoul'
    pull-request-branch-name:
      separator: '-'
    versioning-strategy: 'increase'

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: 'github-actions'
    assignees:
      - 'lumirlumir'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    reviewers:
      - 'lumirlumir'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Asia/Seoul'
    pull-request-branch-name:
      separator: '-'
